### ISSUE TITLE
PDF version cuts off skills and possibly other sections

### ISSUE THREAD

**Issue by surfer190** [francescoes/jsonresume-theme-stackoverflow#7] opened 2016-05-14 08:46 UTC
On the PDF version if you have more than 4 sets of skills, the others get cut off.
So the sets of skills are not wrapped around.

I think this might also be the case with interest and maybe others.

Let me know where I should start and I can try figure it out

**Comment by francescoes** [comment] 2016-05-17 20:20
in the file `style.css`, the `@media print` refers to the pdf version, so you can check that section to improve it, in this case I will assign the bug to you. 
Otherwise I can have a look over the weekend. 
Cheers

**Comment by francescoes** [comment] 2016-05-22 11:24
Could provide a screenshot? I cannot reproduce this

**Comment by surfer190** [comment] 2016-05-22 11:30
![image](https://cloud.githubusercontent.com/assets/3285222/15453753/65c3aae4-2021-11e6-8e08-e5f72f09841c.png)

**Comment by francescoes** [comment] 2016-05-22 17:03
I am not currently using the `resume-cli` export for the PDF version. 
To export in PDF, please just print the page from the browser and save in PDF, it will look quite different from this. Let me know so that I can close this issue

**Closed** 2016-05-27 11:30 UTC
Labels: bug

**Comment by pabit** [comment] 2016-09-16 11:49
I use hackmyresume and this bug still exist, does not help to change in style.css and when i try to print html page to pdf with cups-pdf theres no bars, if i use wkhtmltopdf bars is cut off  :/ it's possible to fix it?
